package pagina;
// Generated 5/03/2016 01:22:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String contrasenia;
     private Set infos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String usuario) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
    }
    public Usuario(int idUsuario, String usuario, String contrasenia, Set infos) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.infos = infos;
    }
   
     @Id 

    
    @Column(name="idUsuario", nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="usuario", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasenia", length=50)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getInfos() {
        return this.infos;
    }
    
    public void setInfos(Set infos) {
        this.infos = infos;
    }




}


