package pagina;
// Generated 5/03/2016 01:22:12 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Info generated by hbm2java
 */
@Entity
@Table(name="info"
    ,schema="public"
)
public class Info  implements java.io.Serializable {


     private int idInfo;
     private Usuario usuario;
     private String correo;
     private String nombre;
     private String apellido;

    public Info() {
    }

	
    public Info(int idInfo, String correo) {
        this.idInfo = idInfo;
        this.correo = correo;
    }
    public Info(int idInfo, Usuario usuario, String correo, String nombre, String apellido) {
       this.idInfo = idInfo;
       this.usuario = usuario;
       this.correo = correo;
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
     @Id 

    
    @Column(name="IdInfo", nullable=false)
    public int getIdInfo() {
        return this.idInfo;
    }
    
    public void setIdInfo(int idInfo) {
        this.idInfo = idInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="correo", nullable=false, length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


