package Pagina;
// Generated 22/03/2016 07:22:25 PM by Hibernate Tools 4.3.1



/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private int idInfo;
     private Usuario usuario;
     private String correo;
     private String nombre;
     private String apellido;

    public Info() {
    }

	
    public Info(int idInfo, String correo) {
        this.idInfo = idInfo;
        this.correo = correo;
    }
    public Info(int idInfo, Usuario usuario, String correo, String nombre, String apellido) {
       this.idInfo = idInfo;
       this.usuario = usuario;
       this.correo = correo;
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
    public int getIdInfo() {
        return this.idInfo;
    }
    
    public void setIdInfo(int idInfo) {
        this.idInfo = idInfo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


