package Pagina;
// Generated 22/03/2016 01:55:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String contrasenia;
     private Set<Info> infos = new HashSet<Info>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String usuario) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
    }
    public Usuario(int idUsuario, String usuario, String contrasenia, Set<Info> infos) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.infos = infos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set<Info> getInfos() {
        return this.infos;
    }
    
    public void setInfos(Set<Info> infos) {
        this.infos = infos;
    }




}


